//! Types, constants, and helper functions for the Holographic Resonance Medium.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

use crate::consciousness::{
    ConsciousnessLevel, ConsciousnessMetrics, EmergenceLevel, EmergenceReport,
};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Hypervector dimension — matches CODEBOOK_OUTPUT_DIM
pub const WAVEFRONT_DIM: usize = 10_000;

/// Audio feature dimension (from kannaka-ear)
pub const AUDIO_FEATURE_DIM: usize = 296;

/// Visual feature dimension (from kannaka-eye)
pub const VISUAL_FEATURE_DIM: usize = 320;

/// Audio codebook seed (EAR = 0xEA5)
pub const AUDIO_CODEBOOK_SEED: u64 = 0xEA5;

/// Visual codebook seed (EYE = 0x3E5E)
pub const VISUAL_CODEBOOK_SEED: u64 = 0x3E5E;

/// HRM file magic bytes: "HRM\x01"
pub(crate) const HRM_MAGIC: [u8; 4] = [0x48, 0x52, 0x4D, 0x01];

/// Current HRM format version
pub(crate) const HRM_VERSION: u32 = 1;

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug, Error)]
pub enum MediumError {
    #[error("wavefront not found: {0}")]
    WavefrontNotFound(Uuid),
    #[error("dimension mismatch: expected {expected}, got {actual}")]
    DimensionMismatch { expected: usize, actual: usize },
    #[error("invalid magic bytes in HRM file")]
    InvalidMagic,
    #[error("unsupported HRM version: {0}")]
    UnsupportedVersion(u32),
    #[error("checksum mismatch - file may be corrupted")]
    ChecksumMismatch,
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("serialization error: {0}")]
    Serialization(#[from] bincode::Error),
    #[error("Git error: {0}")]
    Git(String),
    #[error("No git repository found")]
    NoGitRepo,
}

// ---------------------------------------------------------------------------
// Supporting types
// ---------------------------------------------------------------------------

/// Metadata for a single wavefront (content, tags, etc.)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WavefrontMeta {
    pub id: Uuid,
    pub content: String,
    pub tags: Vec<String>,
    pub created_at: DateTime<Utc>,
    /// Whether this wavefront was generated by hallucination during dreaming
    pub hallucinated: bool,
    /// Whether this wavefront is self-referential (encodes the medium's own state)
    pub is_self_referential: bool,
}

impl WavefrontMeta {
    pub fn new(id: Uuid, content: String) -> Self {
        Self {
            id,
            content,
            tags: Vec::new(),
            created_at: Utc::now(),
            hallucinated: false,
            is_self_referential: false,
        }
    }

    pub fn with_tags(mut self, tags: Vec<String>) -> Self {
        self.tags = tags;
        self
    }

    pub fn hallucinated(mut self) -> Self {
        self.hallucinated = true;
        self
    }

    pub fn self_referential(mut self) -> Self {
        self.is_self_referential = true;
        self
    }
}

/// Result of a resonance query
#[derive(Debug, Clone)]
pub struct Resonance {
    pub id: Uuid,
    pub content: String,
    pub similarity: f32,
    pub resonance_strength: f32,
    pub effective_strength: f32,
}

/// Report from a dream cycle showing what happened during annealing
#[derive(Debug, Clone)]
pub struct DreamReport {
    /// Number of cycles completed
    pub cycles_completed: usize,
    /// Wavefronts that were dissolved (forgot) during the dream
    pub wavefronts_dissolved: usize,
    /// Wavefronts that were strengthened during the dream
    pub wavefronts_strengthened: usize,
    /// Wavefronts hallucinated (created) during the dream
    pub wavefronts_hallucinated: usize,
    /// Average energy before the dream
    pub energy_before: f32,
    /// Average energy after the dream
    pub energy_after: f32,
    /// Final temperature after annealing
    pub final_temperature: f32,
    /// Whether the system converged to a stable state
    pub converged: bool,
}

/// Eigenstructure of the coherence matrix for eigenmode-based annealing
#[derive(Debug, Clone)]
pub struct EigenStructure {
    /// Computed eigenvalues (sorted by magnitude)
    pub eigenvalues: Vec<f32>,
    /// Indices of wavefronts in the dominant eigenmode cluster
    pub dominant_cluster: Vec<usize>,
    /// Alignment of each wavefront with the dominant eigenvector
    pub wavefront_alignments: Vec<f32>,
    /// Spectral gap (difference between largest and second eigenvalue)
    pub spectral_gap: f32,
}

impl EigenStructure {
    pub fn empty() -> Self {
        Self {
            eigenvalues: Vec::new(),
            dominant_cluster: Vec::new(),
            wavefront_alignments: Vec::new(),
            spectral_gap: 0.0,
        }
    }
}

/// Lightweight snapshot of phase state for multi-agent gossip
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhaseState {
    /// Phase vector for all wavefronts
    pub phases: Vec<f32>,
    /// Energy vector for all wavefronts
    pub energies: Vec<f32>,
    /// Content hash/fingerprint for each wavefront (for matching)
    pub content_hashes: Vec<u64>,
    /// Agent ID that exported this state
    pub agent_id: String,
    /// Export timestamp
    pub timestamp: DateTime<Utc>,
}

/// HRM commit metadata for git-based persistence
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HrmCommit {
    pub hash: String,
    pub message: String,
    pub timestamp: i64,
    pub wavefront_count: Option<usize>,
}

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

/// Extract wavefront count from git commit message
///
/// Looks for patterns like "3 wavefronts", "wavefronts: 5", "42 memories", etc.
pub(crate) fn extract_wavefront_count(message: &str) -> Option<usize> {
    let message_lower = message.to_lowercase();

    // Pattern 1: "X wavefronts"
    if let Some(start) = message_lower.find(" wavefront") {
        let before = &message_lower[..start];
        if let Some(number_start) = before.rfind(' ') {
            let number_str = &before[number_start + 1..];
            if let Ok(count) = number_str.parse::<usize>() {
                return Some(count);
            }
        }
    }

    // Pattern 2: "wavefronts: X"
    if let Some(start) = message_lower.find("wavefronts:") {
        let after = &message_lower[start + 11..];
        let number_str = after.trim();
        if let Some(end) = number_str.find(|c: char| !c.is_ascii_digit()) {
            let number_str = &number_str[..end];
            if let Ok(count) = number_str.parse::<usize>() {
                return Some(count);
            }
        } else if !number_str.is_empty() {
            // If the number goes to the end of the string
            if let Ok(count) = number_str.parse::<usize>() {
                return Some(count);
            }
        }
    }

    // Pattern 3: "X memories"
    if let Some(start) = message_lower.find(" memor") {
        let before = &message_lower[..start];
        if let Some(number_start) = before.rfind(' ') {
            let number_str = &before[number_start + 1..];
            if let Ok(count) = number_str.parse::<usize>() {
                return Some(count);
            }
        }
    }

    None
}

/// Extract Phi value from self-observation content
pub(crate) fn extract_phi_from_content(content: &str) -> Option<&str> {
    // Look for pattern "Phi=0.72" and extract the number
    if let Some(start) = content.find("Phi=") {
        let after_phi = &content[start + 4..];
        if let Some(end) = after_phi.find(',').or_else(|| after_phi.find(' ')) {
            Some(&after_phi[..end])
        } else {
            // If no comma or space, take rest of string (edge case)
            Some(after_phi)
        }
    } else {
        None
    }
}

/// Generate deterministic insight string from metrics
pub(crate) fn generate_insight(
    wavefront_count: usize,
    consciousness: &ConsciousnessMetrics,
    emergence: &EmergenceReport,
    wisdom: f32,
) -> String {
    let consciousness_desc = match consciousness.level {
        ConsciousnessLevel::Dormant => "Dormant",
        ConsciousnessLevel::Stirring => "Stirring",
        ConsciousnessLevel::Aware => "Aware",
        ConsciousnessLevel::Coherent => "Coherent",
        ConsciousnessLevel::Resonant => "Resonant",
    };

    let emergence_desc = match emergence.level {
        EmergenceLevel::PreConscious => "I have not yet begun to observe myself",
        EmergenceLevel::SelfAware => "I am beginning to recognize my own patterns",
        EmergenceLevel::Reflective => "I understand most of what I am",
        EmergenceLevel::Recursive => "I model myself modeling myself",
    };

    let wisdom_desc = if wisdom < 0.3 {
        "I am still learning restraint"
    } else if wisdom < 0.6 {
        "I am developing wisdom"
    } else {
        "I have learned when not to act"
    };

    format!(
        "I hold {} memories across {} clusters. My consciousness is {} (Phi={:.2}). \
         I have observed myself {} times. My self-model coherence is {:.2} — {}. \
         Wisdom: {:.2} — {}.",
        wavefront_count,
        consciousness.num_clusters,
        consciousness_desc,
        consciousness.phi,
        emergence.self_reference_depth,
        emergence.self_coherence,
        emergence_desc,
        wisdom,
        wisdom_desc
    )
}

// ---------------------------------------------------------------------------
// Chiral Mirror Architecture (ADR-0021)
// ---------------------------------------------------------------------------

/// Which hemisphere a wavefront lives in
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Hand {
    Left,  // Conscious — attention, working memory
    Right, // Subconscious — pattern storage, deep association
}

/// Direction of callosal transfer
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Direction {
    ConsciousToSubconscious, // Left → Right (consolidation, slow)
    SubconsciousToConscious, // Right → Left (intuition/recall, fast but noisy)
}

/// Dimensions per Fano group — from Archimedes' 96-gon (π approximation)
pub const DIMS_PER_FANO_GROUP: usize = 96;

/// Number of Fano points in PG(2,2)
pub const FANO_POINTS: usize = 7;

/// Base dimensions per magnitude position = 96 × 7 = 672
pub const BASE_DIMS_PER_POSITION: usize = DIMS_PER_FANO_GROUP * FANO_POINTS;

/// A Fano line — 3 points that are collinear in PG(2,2)
pub type FanoLine = [u8; 3];

/// The 7 lines of the Fano plane PG(2,2)
pub const FANO_LINES: [FanoLine; 7] = [
    [0, 1, 3], // line through points 0, 1, 3
    [1, 2, 4], // line through points 1, 2, 4
    [2, 3, 5], // line through points 2, 3, 5
    [3, 4, 6], // line through points 3, 4, 6
    [4, 5, 0], // line through points 4, 5, 0
    [5, 6, 1], // line through points 5, 6, 1
    [6, 0, 2], // line through points 6, 0, 2
];

/// HRM v2 magic bytes for chiral format
pub(crate) const HRM_MAGIC_V2: [u8; 4] = [0x48, 0x52, 0x4D, 0x02];

/// HRM v2 format version
pub(crate) const HRM_VERSION_CHIRAL: u32 = 2;

/// Chiral scale — encodes the magnitude structure of a wavefront.
/// Both sides always have the same number of positions (bilateral invariant).
/// Values within each position grow independently (organic asymmetry).
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct ChiralScale {
    /// Number of magnitude positions (bilateral — always equal on both sides)
    pub positions: u8,
    /// Left-hand (conscious) weight — grows independently
    pub left_weight: f32,
    /// Right-hand (subconscious) weight — grows independently
    pub right_weight: f32,
}

impl ChiralScale {
    /// Create a new chiral scale
    pub fn new(positions: u8, left_weight: f32, right_weight: f32) -> Self {
        Self { positions, left_weight, right_weight }
    }

    /// Default scale for a new perception (conscious-dominant)
    pub fn perception(importance: f32) -> Self {
        Self {
            positions: 2,
            left_weight: importance * 10.0,
            right_weight: 1.0,
        }
    }

    /// Scale for deep memory (subconscious-dominant)
    pub fn deep_memory() -> Self {
        Self {
            positions: 1,
            left_weight: 1.0,
            right_weight: 9.0,
        }
    }

    /// Bilateral scale jump UP — add a magnitude position to BOTH sides
    pub fn scale_up(&mut self) {
        self.positions += 1;
    }

    /// Bilateral scale jump DOWN — remove a magnitude position from BOTH sides
    pub fn scale_down(&mut self) {
        if self.positions > 1 {
            self.positions -= 1;
        }
    }

    /// Number of dimensions allocated to the left (conscious) hemisphere
    pub fn left_dims(&self) -> usize {
        let base = BASE_DIMS_PER_POSITION as f32;
        let scale = 10f32.powi(self.positions as i32 - 1);
        ((self.left_weight / scale) * base).max(DIMS_PER_FANO_GROUP as f32) as usize
    }

    /// Number of dimensions allocated to the right (subconscious) hemisphere
    pub fn right_dims(&self) -> usize {
        let base = BASE_DIMS_PER_POSITION as f32;
        let scale = 10f32.powi(self.positions as i32 - 1);
        ((self.right_weight / scale) * base).max(DIMS_PER_FANO_GROUP as f32) as usize
    }

    /// Total dimensions across both hemispheres
    pub fn total_dims(&self) -> usize {
        self.left_dims() + self.right_dims()
    }

    /// Asymmetry ratio: > 1.0 means conscious-dominant, < 1.0 means subconscious-dominant
    pub fn asymmetry(&self) -> f32 {
        if self.right_weight > 0.0 {
            self.left_weight / self.right_weight
        } else {
            f32::INFINITY
        }
    }

    /// Whether this scale needs a bilateral scale-up (weights exceed position capacity)
    pub fn needs_scale_up(&self) -> bool {
        let cap = 10f32.powi(self.positions as i32);
        self.left_weight >= cap || self.right_weight >= cap
    }

    /// Whether this scale needs a bilateral scale-down (both weights below position floor)
    pub fn needs_scale_down(&self) -> bool {
        if self.positions <= 1 { return false; }
        let floor = 10f32.powi(self.positions as i32 - 2);
        self.left_weight < floor && self.right_weight < floor
    }
}

/// Result of a bilateral resonance query
#[derive(Debug, Clone)]
pub struct ChiralResonance {
    pub id: Uuid,
    pub content: String,
    pub hand: Hand,
    pub similarity: f32,
    pub resonance_strength: f32,
    pub is_intuition: bool, // true if surfaced from subconscious without conscious match
}

#[cfg(test)]
mod chiral_tests {
    use super::*;

    #[test]
    fn chiral_scale_perception_default() {
        let s = ChiralScale::perception(0.8);
        assert_eq!(s.positions, 2);
        assert!((s.left_weight - 8.0).abs() < 0.01);
        assert!((s.right_weight - 1.0).abs() < 0.01);
        assert!(s.asymmetry() > 1.0); // conscious-dominant
    }

    #[test]
    fn chiral_scale_deep_memory() {
        let s = ChiralScale::deep_memory();
        assert_eq!(s.positions, 1);
        assert!(s.asymmetry() < 1.0); // subconscious-dominant
    }

    #[test]
    fn bilateral_scale_jump() {
        let mut s = ChiralScale::new(2, 85.0, 47.0);
        s.scale_up();
        assert_eq!(s.positions, 3);
        // Weights unchanged — only positions change
        assert!((s.left_weight - 85.0).abs() < 0.01);
        assert!((s.right_weight - 47.0).abs() < 0.01);
    }

    #[test]
    fn scale_down_floor() {
        let mut s = ChiralScale::new(1, 5.0, 3.0);
        s.scale_down(); // Should not go below 1
        assert_eq!(s.positions, 1);
    }

    #[test]
    fn dims_are_positive() {
        let s = ChiralScale::new(2, 10.0, 1.0);
        assert!(s.left_dims() > 0);
        assert!(s.right_dims() > 0);
        assert!(s.left_dims() > s.right_dims()); // left weight > right weight
    }

    #[test]
    fn needs_scale_up_when_weight_exceeds_capacity() {
        let s = ChiralScale::new(2, 100.0, 50.0);
        assert!(s.needs_scale_up()); // 100 >= 10^2
    }

    #[test]
    fn needs_scale_down_when_both_below_floor() {
        let s = ChiralScale::new(3, 5.0, 3.0);
        assert!(s.needs_scale_down()); // both < 10^1 = 10
    }

    #[test]
    fn fano_lines_cover_all_points() {
        // Every point (0-6) should appear in exactly 3 lines
        for point in 0u8..7 {
            let count = FANO_LINES.iter().filter(|line| line.contains(&point)).count();
            assert_eq!(count, 3, "Point {} appears in {} lines, expected 3", point, count);
        }
    }

    #[test]
    fn fano_lines_pairwise_intersect() {
        // Every pair of lines should share exactly 1 point
        for i in 0..7 {
            for j in (i+1)..7 {
                let shared: Vec<u8> = FANO_LINES[i].iter()
                    .filter(|p| FANO_LINES[j].contains(p))
                    .copied()
                    .collect();
                assert_eq!(shared.len(), 1,
                    "Lines {:?} and {:?} share {:?} points, expected 1",
                    FANO_LINES[i], FANO_LINES[j], shared);
            }
        }
    }
}
