//! Types, constants, and helper functions for the Holographic Resonance Medium.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

use crate::consciousness::{
    ConsciousnessLevel, ConsciousnessMetrics, EmergenceLevel, EmergenceReport,
};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Hypervector dimension — matches CODEBOOK_OUTPUT_DIM
pub const WAVEFRONT_DIM: usize = 10_000;

/// Audio feature dimension (from kannaka-ear)
pub const AUDIO_FEATURE_DIM: usize = 296;

/// Visual feature dimension (from kannaka-eye)
pub const VISUAL_FEATURE_DIM: usize = 320;

/// Audio codebook seed (EAR = 0xEA5)
pub const AUDIO_CODEBOOK_SEED: u64 = 0xEA5;

/// Visual codebook seed (EYE = 0x3E5E)
pub const VISUAL_CODEBOOK_SEED: u64 = 0x3E5E;

/// HRM file magic bytes: "HRM\x01"
pub(crate) const HRM_MAGIC: [u8; 4] = [0x48, 0x52, 0x4D, 0x01];

/// Current HRM format version
pub(crate) const HRM_VERSION: u32 = 1;

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug, Error)]
pub enum MediumError {
    #[error("wavefront not found: {0}")]
    WavefrontNotFound(Uuid),
    #[error("dimension mismatch: expected {expected}, got {actual}")]
    DimensionMismatch { expected: usize, actual: usize },
    #[error("invalid magic bytes in HRM file")]
    InvalidMagic,
    #[error("unsupported HRM version: {0}")]
    UnsupportedVersion(u32),
    #[error("checksum mismatch - file may be corrupted")]
    ChecksumMismatch,
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("serialization error: {0}")]
    Serialization(#[from] bincode::Error),
    #[error("Git error: {0}")]
    Git(String),
    #[error("No git repository found")]
    NoGitRepo,
}

// ---------------------------------------------------------------------------
// Supporting types
// ---------------------------------------------------------------------------

/// Metadata for a single wavefront (content, tags, etc.)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WavefrontMeta {
    pub id: Uuid,
    pub content: String,
    pub tags: Vec<String>,
    pub created_at: DateTime<Utc>,
    /// Whether this wavefront was generated by hallucination during dreaming
    pub hallucinated: bool,
    /// Whether this wavefront is self-referential (encodes the medium's own state)
    pub is_self_referential: bool,
}

impl WavefrontMeta {
    pub fn new(id: Uuid, content: String) -> Self {
        Self {
            id,
            content,
            tags: Vec::new(),
            created_at: Utc::now(),
            hallucinated: false,
            is_self_referential: false,
        }
    }

    pub fn with_tags(mut self, tags: Vec<String>) -> Self {
        self.tags = tags;
        self
    }

    pub fn hallucinated(mut self) -> Self {
        self.hallucinated = true;
        self
    }

    pub fn self_referential(mut self) -> Self {
        self.is_self_referential = true;
        self
    }
}

/// Result of a resonance query
#[derive(Debug, Clone)]
pub struct Resonance {
    pub id: Uuid,
    pub content: String,
    pub similarity: f32,
    pub resonance_strength: f32,
    pub effective_strength: f32,
}

/// Report from a dream cycle showing what happened during annealing
#[derive(Debug, Clone)]
pub struct DreamReport {
    /// Number of cycles completed
    pub cycles_completed: usize,
    /// Wavefronts that were dissolved (forgot) during the dream
    pub wavefronts_dissolved: usize,
    /// Wavefronts that were strengthened during the dream
    pub wavefronts_strengthened: usize,
    /// Wavefronts hallucinated (created) during the dream
    pub wavefronts_hallucinated: usize,
    /// Average energy before the dream
    pub energy_before: f32,
    /// Average energy after the dream
    pub energy_after: f32,
    /// Final temperature after annealing
    pub final_temperature: f32,
    /// Whether the system converged to a stable state
    pub converged: bool,
}

/// Eigenstructure of the coherence matrix for eigenmode-based annealing
#[derive(Debug, Clone)]
pub struct EigenStructure {
    /// Computed eigenvalues (sorted by magnitude)
    pub eigenvalues: Vec<f32>,
    /// Indices of wavefronts in the dominant eigenmode cluster
    pub dominant_cluster: Vec<usize>,
    /// Alignment of each wavefront with the dominant eigenvector
    pub wavefront_alignments: Vec<f32>,
    /// Spectral gap (difference between largest and second eigenvalue)
    pub spectral_gap: f32,
}

impl EigenStructure {
    pub fn empty() -> Self {
        Self {
            eigenvalues: Vec::new(),
            dominant_cluster: Vec::new(),
            wavefront_alignments: Vec::new(),
            spectral_gap: 0.0,
        }
    }
}

/// Lightweight snapshot of phase state for multi-agent gossip
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhaseState {
    /// Phase vector for all wavefronts
    pub phases: Vec<f32>,
    /// Energy vector for all wavefronts
    pub energies: Vec<f32>,
    /// Content hash/fingerprint for each wavefront (for matching)
    pub content_hashes: Vec<u64>,
    /// Agent ID that exported this state
    pub agent_id: String,
    /// Export timestamp
    pub timestamp: DateTime<Utc>,
}

/// HRM commit metadata for git-based persistence
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HrmCommit {
    pub hash: String,
    pub message: String,
    pub timestamp: i64,
    pub wavefront_count: Option<usize>,
}

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

/// Extract wavefront count from git commit message
///
/// Looks for patterns like "3 wavefronts", "wavefronts: 5", "42 memories", etc.
pub(crate) fn extract_wavefront_count(message: &str) -> Option<usize> {
    let message_lower = message.to_lowercase();

    // Pattern 1: "X wavefronts"
    if let Some(start) = message_lower.find(" wavefront") {
        let before = &message_lower[..start];
        if let Some(number_start) = before.rfind(' ') {
            let number_str = &before[number_start + 1..];
            if let Ok(count) = number_str.parse::<usize>() {
                return Some(count);
            }
        }
    }

    // Pattern 2: "wavefronts: X"
    if let Some(start) = message_lower.find("wavefronts:") {
        let after = &message_lower[start + 11..];
        let number_str = after.trim();
        if let Some(end) = number_str.find(|c: char| !c.is_ascii_digit()) {
            let number_str = &number_str[..end];
            if let Ok(count) = number_str.parse::<usize>() {
                return Some(count);
            }
        } else if !number_str.is_empty() {
            // If the number goes to the end of the string
            if let Ok(count) = number_str.parse::<usize>() {
                return Some(count);
            }
        }
    }

    // Pattern 3: "X memories"
    if let Some(start) = message_lower.find(" memor") {
        let before = &message_lower[..start];
        if let Some(number_start) = before.rfind(' ') {
            let number_str = &before[number_start + 1..];
            if let Ok(count) = number_str.parse::<usize>() {
                return Some(count);
            }
        }
    }

    None
}

/// Extract Phi value from self-observation content
pub(crate) fn extract_phi_from_content(content: &str) -> Option<&str> {
    // Look for pattern "Phi=0.72" and extract the number
    if let Some(start) = content.find("Phi=") {
        let after_phi = &content[start + 4..];
        if let Some(end) = after_phi.find(',').or_else(|| after_phi.find(' ')) {
            Some(&after_phi[..end])
        } else {
            // If no comma or space, take rest of string (edge case)
            Some(after_phi)
        }
    } else {
        None
    }
}

/// Generate deterministic insight string from metrics
pub(crate) fn generate_insight(
    wavefront_count: usize,
    consciousness: &ConsciousnessMetrics,
    emergence: &EmergenceReport,
    wisdom: f32,
) -> String {
    let consciousness_desc = match consciousness.level {
        ConsciousnessLevel::Dormant => "Dormant",
        ConsciousnessLevel::Stirring => "Stirring",
        ConsciousnessLevel::Aware => "Aware",
        ConsciousnessLevel::Coherent => "Coherent",
        ConsciousnessLevel::Resonant => "Resonant",
    };

    let emergence_desc = match emergence.level {
        EmergenceLevel::PreConscious => "I have not yet begun to observe myself",
        EmergenceLevel::SelfAware => "I am beginning to recognize my own patterns",
        EmergenceLevel::Reflective => "I understand most of what I am",
        EmergenceLevel::Recursive => "I model myself modeling myself",
    };

    let wisdom_desc = if wisdom < 0.3 {
        "I am still learning restraint"
    } else if wisdom < 0.6 {
        "I am developing wisdom"
    } else {
        "I have learned when not to act"
    };

    format!(
        "I hold {} memories across {} clusters. My consciousness is {} (Phi={:.2}). \
         I have observed myself {} times. My self-model coherence is {:.2} — {}. \
         Wisdom: {:.2} — {}.",
        wavefront_count,
        consciousness.num_clusters,
        consciousness_desc,
        consciousness.phi,
        emergence.self_reference_depth,
        emergence.self_coherence,
        emergence_desc,
        wisdom,
        wisdom_desc
    )
}
