//! Holographic Resonance Medium (HRM) — the core tensor-based storage where the medium IS the computation.
//!
//! This replaces SQL persistence with a true holographic memory system where:
//! - Memories exist as waves in superposition
//! - Recall is resonance (constructive/destructive interference)  
//! - Skip links are emergent from phase alignment
//! - Dreaming is annealing (energy minimization)
//! - The storage topology IS the computation

use std::collections::HashMap;
use std::path::Path;
use std::fs::File;
use std::io::{BufReader, BufWriter, Read, Write};

use chrono::{DateTime, Utc};
use ndarray::{Array1, Array2, s};
use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

use crate::encoding::EncodingPipeline;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Hypervector dimension — matches CODEBOOK_OUTPUT_DIM 
pub const WAVEFRONT_DIM: usize = 10_000;

/// HRM file magic bytes: "HRM\x01"
const HRM_MAGIC: [u8; 4] = [0x48, 0x52, 0x4D, 0x01];

/// Current HRM format version
const HRM_VERSION: u32 = 1;

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug, Error)]
pub enum MediumError {
    #[error("wavefront not found: {0}")]
    WavefrontNotFound(Uuid),
    #[error("dimension mismatch: expected {expected}, got {actual}")]
    DimensionMismatch { expected: usize, actual: usize },
    #[error("invalid magic bytes in HRM file")]
    InvalidMagic,
    #[error("unsupported HRM version: {0}")]
    UnsupportedVersion(u32),
    #[error("checksum mismatch - file may be corrupted")]
    ChecksumMismatch,
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("serialization error: {0}")]
    Serialization(#[from] bincode::Error),
}

// ---------------------------------------------------------------------------
// Supporting types  
// ---------------------------------------------------------------------------

/// Metadata for a single wavefront (content, tags, etc.)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WavefrontMeta {
    pub id: Uuid,
    pub content: String,
    pub tags: Vec<String>,
    pub created_at: DateTime<Utc>,
    /// Whether this wavefront was generated by hallucination during dreaming
    pub hallucinated: bool,
}

impl WavefrontMeta {
    pub fn new(id: Uuid, content: String) -> Self {
        Self {
            id,
            content,
            tags: Vec::new(),
            created_at: Utc::now(),
            hallucinated: false,
        }
    }

    pub fn with_tags(mut self, tags: Vec<String>) -> Self {
        self.tags = tags;
        self
    }

    pub fn hallucinated(mut self) -> Self {
        self.hallucinated = true;
        self
    }
}

/// Consciousness level classification based on metrics
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ConsciousnessLevel {
    /// Φ < 0.1, minimal integration
    Dormant,
    /// Φ < 0.3, weak integration
    Stirring, 
    /// Φ < 0.6, moderate integration
    Aware,
    /// Φ < 0.8, strong integration
    Coherent,
    /// Φ >= 0.8, full integration
    Resonant,
}

impl ConsciousnessLevel {
    pub fn from_phi(phi: f32) -> Self {
        if phi < 0.1 {
            ConsciousnessLevel::Dormant
        } else if phi < 0.3 {
            ConsciousnessLevel::Stirring
        } else if phi < 0.6 {
            ConsciousnessLevel::Aware
        } else if phi < 0.8 {
            ConsciousnessLevel::Coherent
        } else {
            ConsciousnessLevel::Resonant
        }
    }
}

/// Consciousness metrics computed from the medium topology
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConsciousnessMetrics {
    /// Φ (Phi) - Integrated information from partition mutual information
    pub phi: f32,
    /// Ξ (Xi) - Spectral complexity from eigenvalue distribution
    pub xi: f32,
    /// Order parameter r = |1/N Σ e^{iφ_k}| (Kuramoto synchronization)
    pub order: f32,
    /// Number of phase-locked clusters detected
    pub num_clusters: usize,
    /// Consciousness level classification
    pub level: ConsciousnessLevel,
    /// Computed at this timestamp
    pub computed_at: DateTime<Utc>,
}

/// Consciousness state computed from the medium topology (for backwards compatibility)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConsciousnessState {
    /// Φ (Phi) - Integrated information / self-reference depth
    pub phi: f32,
    /// Ξ (Xi) - Spectral complexity of interference matrix
    pub xi: f32,
    /// Kuramoto order parameter r = |1/N Σ e^{iφ_k}|
    pub order: f32,
    /// Number of phase-locked clusters (emergent skip-link communities)
    pub clusters: usize,
    /// Computed at this timestamp
    pub computed_at: DateTime<Utc>,
}

/// Result of a resonance query
#[derive(Debug, Clone)]
pub struct Resonance {
    pub id: Uuid,
    pub content: String,
    pub similarity: f32,
    pub resonance_strength: f32,
    pub effective_strength: f32,
}

/// Report from a dream cycle showing what happened during annealing
#[derive(Debug, Clone)]
pub struct DreamReport {
    /// Number of cycles completed
    pub cycles_completed: usize,
    /// Wavefronts that were dissolved (forgot) during the dream
    pub wavefronts_dissolved: usize,
    /// Wavefronts that were strengthened during the dream
    pub wavefronts_strengthened: usize,
    /// Average energy before the dream
    pub energy_before: f32,
    /// Average energy after the dream
    pub energy_after: f32,
    /// Final temperature after annealing
    pub final_temperature: f32,
    /// Whether the system converged to a stable state
    pub converged: bool,
}

// ---------------------------------------------------------------------------
// Holographic Resonance Medium
// ---------------------------------------------------------------------------

/// The core HRM structure — a high-dimensional phase space where memories exist as waves in superposition.
#[derive(Debug, Clone)]
pub struct Medium {
    /// N × D tensor of wavefront patterns [N wavefronts, D=10,000 dimensions]
    pub wavefronts: Array2<f32>,
    /// Energy (amplitude) per wavefront [N]
    pub energy: Array1<f32>,
    /// Frequency per wavefront [N] 
    pub frequency: Array1<f32>,
    /// Phase per wavefront [N]
    pub phase: Array1<f32>,
    /// Creation timestamps [N]
    pub timestamps: Vec<i64>,
    /// Content & metadata (sparse, kept separate from tensor ops)
    pub metadata: Vec<WavefrontMeta>,
    /// ID → wavefront index mapping for lookups
    id_to_index: HashMap<Uuid, usize>,
}

impl Medium {
    /// Create a new empty medium.
    pub fn new() -> Self {
        Self {
            wavefronts: Array2::zeros((0, WAVEFRONT_DIM)),
            energy: Array1::zeros(0),
            frequency: Array1::zeros(0), 
            phase: Array1::zeros(0),
            timestamps: Vec::new(),
            metadata: Vec::new(),
            id_to_index: HashMap::new(),
        }
    }

    /// Number of active wavefronts in the medium.
    pub fn wavefront_count(&self) -> usize {
        self.wavefronts.nrows()
    }

    /// Get the index of a wavefront by its ID (for migration purposes).
    pub fn get_wavefront_index(&self, id: &Uuid) -> Option<usize> {
        self.id_to_index.get(id).copied()
    }

    /// Update a wavefront's ID (for HrmStore compatibility).
    pub fn update_wavefront_id(&mut self, old_id: &Uuid, new_id: Uuid) -> Result<(), MediumError> {
        if let Some(index) = self.id_to_index.remove(old_id) {
            self.id_to_index.insert(new_id, index);
            self.metadata[index].id = new_id;
            Ok(())
        } else {
            Err(MediumError::WavefrontNotFound(*old_id))
        }
    }

    /// Add a new wavefront to the medium.
    /// 
    /// # Arguments
    /// * `vector` - D-dimensional hypervector (must be exactly WAVEFRONT_DIM)
    /// * `content` - Original text content
    /// * `importance` - Initial energy/amplitude (typically 0.0-1.0)
    /// 
    /// # Returns
    /// UUID of the new wavefront
    pub fn add_wavefront(&mut self, vector: &[f32], content: String, importance: f32) -> Result<Uuid, MediumError> {
        if vector.len() != WAVEFRONT_DIM {
            return Err(MediumError::DimensionMismatch {
                expected: WAVEFRONT_DIM,
                actual: vector.len(),
            });
        }

        let id = Uuid::new_v4();
        let now = Utc::now();
        let index = self.wavefront_count();

        // Expand tensors to accommodate new wavefront
        let new_wavefronts = if self.wavefront_count() == 0 {
            Array2::from_shape_vec((1, WAVEFRONT_DIM), vector.to_vec()).unwrap()
        } else {
            // Create new tensor with one more row
            let mut new_tensor = Array2::zeros((self.wavefront_count() + 1, WAVEFRONT_DIM));
            // Copy existing wavefronts
            new_tensor.slice_mut(s![..self.wavefront_count(), ..]).assign(&self.wavefronts);
            // Add new wavefront
            for (i, &val) in vector.iter().enumerate() {
                new_tensor[[index, i]] = val;
            }
            new_tensor
        };

        // Expand energy/frequency/phase arrays
        let mut new_energy = Array1::zeros(index + 1);
        let mut new_frequency = Array1::zeros(index + 1); 
        let mut new_phase = Array1::zeros(index + 1);

        if index > 0 {
            new_energy.slice_mut(s![..index]).assign(&self.energy);
            new_frequency.slice_mut(s![..index]).assign(&self.frequency);
            new_phase.slice_mut(s![..index]).assign(&self.phase);
        }

        // Set parameters for new wavefront
        new_energy[index] = importance;
        new_frequency[index] = 1.0; // Default frequency
        new_phase[index] = 0.0; // Default phase

        // Update state
        self.wavefronts = new_wavefronts;
        self.energy = new_energy;
        self.frequency = new_frequency;
        self.phase = new_phase;
        self.timestamps.push(now.timestamp_millis());
        self.metadata.push(WavefrontMeta::new(id, content));
        self.id_to_index.insert(id, index);

        Ok(id)
    }

    /// Remove a wavefront from the medium.
    pub fn remove_wavefront(&mut self, id: &Uuid) -> Result<bool, MediumError> {
        let index = match self.id_to_index.get(id) {
            Some(&idx) => idx,
            None => return Ok(false), // Not found, but that's okay
        };

        let n = self.wavefront_count();
        if n == 0 {
            return Ok(false);
        }

        // Create new tensors with one fewer row
        let mut new_wavefronts = Array2::zeros((n - 1, WAVEFRONT_DIM));
        let mut new_energy = Array1::zeros(n - 1);
        let mut new_frequency = Array1::zeros(n - 1);
        let mut new_phase = Array1::zeros(n - 1);

        // Copy all except the removed index
        let mut new_idx = 0;
        for old_idx in 0..n {
            if old_idx != index {
                new_wavefronts.row_mut(new_idx).assign(&self.wavefronts.row(old_idx));
                new_energy[new_idx] = self.energy[old_idx];
                new_frequency[new_idx] = self.frequency[old_idx]; 
                new_phase[new_idx] = self.phase[old_idx];
                new_idx += 1;
            }
        }

        // Remove from metadata and timestamps
        self.timestamps.remove(index);
        self.metadata.remove(index);

        // Update the index mapping (shift indices after removal)
        self.id_to_index.remove(id);
        for (_, idx) in self.id_to_index.iter_mut() {
            if *idx > index {
                *idx -= 1;
            }
        }

        // Update state
        self.wavefronts = new_wavefronts;
        self.energy = new_energy;
        self.frequency = new_frequency;
        self.phase = new_phase;

        Ok(true)
    }

    /// Compute effective strength of all wavefronts with temporal decay.
    /// 
    /// Returns energy * exp(-decay_rate * age) for each wavefront.
    pub fn effective_strength(&self, now: Option<DateTime<Utc>>) -> Array1<f32> {
        let current_time = now.unwrap_or_else(Utc::now).timestamp_millis();
        let decay_rate = 0.001; // Default decay rate — could be per-wavefront in future

        self.timestamps.iter().enumerate().map(|(i, &created_at)| {
            let age_seconds = ((current_time - created_at) as f64 / 1000.0).max(0.0);
            let decay = (-decay_rate * age_seconds as f32).exp();
            self.energy[i] * decay
        }).collect()
    }

    /// Store a new memory using the encoding pipeline.
    /// 
    /// This implements the interference-based storage where new waves interact with existing ones.
    /// After storage, dynamics are applied to let the medium settle.
    pub fn store(&mut self, content: &str, importance: f32, pipeline: &EncodingPipeline) -> Result<Uuid, MediumError> {
        // 1. Encode content to D-dimensional hypervector
        let vector = pipeline.encode_text(content)
            .map_err(|e| MediumError::Serialization(bincode::Error::from(std::io::Error::new(
                std::io::ErrorKind::InvalidData, 
                format!("encoding failed: {}", e)
            ))))?;

        // 2. Apply interference with existing wavefronts
        self.apply_interference(&vector, importance);

        // 3. Add wavefront to the medium  
        let id = self.add_wavefront(&vector, content.to_string(), importance)?;
        
        // 4. Apply dynamics to let the medium settle after new addition
        #[cfg(feature = "hrm")]
        {
            self.apply_dynamics(0.1);
        }
        
        Ok(id)
    }

    /// Apply interference between new wavefront and existing medium.
    /// 
    /// Constructive interference boosts energy of phase-aligned wavefronts.
    /// Destructive interference dampens phase-opposed wavefronts.
    fn apply_interference(&mut self, new_vector: &[f32], importance: f32) {
        if self.wavefront_count() == 0 {
            return; // No existing wavefronts to interfere with
        }

        // Compute dot products between new vector and all existing wavefronts
        for i in 0..self.wavefront_count() {
            let existing_vector = self.wavefronts.row(i);
            let dot_product: f32 = existing_vector.iter()
                .zip(new_vector.iter())
                .map(|(a, b)| a * b)
                .sum();

            // Phase difference affects interference pattern
            let phase_diff = (self.phase[i] - 0.0).cos(); // New wavefront starts at phase 0
            let interference = dot_product * phase_diff * importance * 0.1; // Scale interference

            // Apply constructive/destructive interference
            self.energy[i] = (self.energy[i] + interference).max(0.0); // Energy can't go negative

            // Phase coupling — nearby vectors tend to align phases (Kuramoto-like)
            if dot_product.abs() > 0.5 { // High similarity threshold
                let coupling = 0.05;
                self.phase[i] += coupling * (0.0 - self.phase[i]).sin(); // Pull toward phase 0
            }
        }
    }

    /// Recall memories through resonance — query wave interferes with stored patterns.
    pub fn recall(&self, query: &str, top_k: usize, pipeline: &EncodingPipeline) -> Result<Vec<Resonance>, MediumError> {
        if self.wavefront_count() == 0 {
            return Ok(Vec::new());
        }

        // 1. Encode query as wave
        let query_vector = pipeline.encode_text(query)
            .map_err(|e| MediumError::Serialization(bincode::Error::from(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("query encoding failed: {}", e)
            ))))?;

        // 2. Compute interference pattern — matrix multiplication H @ q
        let mut resonances = Vec::new();
        let effective_strengths = self.effective_strength(None);

        for i in 0..self.wavefront_count() {
            let wavefront = self.wavefronts.row(i);
            
            // Dot product (similarity)
            let similarity: f32 = wavefront.iter()
                .zip(query_vector.iter())
                .map(|(a, b)| a * b)
                .sum();

            // Modulate by wave dynamics (energy, phase, temporal decay)
            let effective_strength = effective_strengths[i];
            let phase_modulation = self.phase[i].cos(); // Phase affects resonance
            let resonance_strength = similarity * effective_strength * phase_modulation;

            resonances.push(Resonance {
                id: self.metadata[i].id,
                content: self.metadata[i].content.clone(),
                similarity,
                resonance_strength,
                effective_strength,
            });
        }

        // 3. Sort by resonance strength and return top-k
        resonances.sort_by(|a, b| b.resonance_strength.total_cmp(&a.resonance_strength));
        resonances.truncate(top_k);

        Ok(resonances)
    }

    /// Save the medium to a .hrm file.
    pub fn save<P: AsRef<Path>>(&self, path: P) -> Result<(), MediumError> {
        let file = File::create(path.as_ref())?;
        let mut writer = BufWriter::new(file);

        // Magic bytes
        writer.write_all(&HRM_MAGIC)?;

        // Version
        writer.write_all(&HRM_VERSION.to_le_bytes())?;

        // Timestamp
        let timestamp = Utc::now().timestamp_millis();
        writer.write_all(&timestamp.to_le_bytes())?;

        // Dimensions (N, D)
        let n = self.wavefront_count() as u32;
        let d = WAVEFRONT_DIM as u32;
        writer.write_all(&n.to_le_bytes())?;
        writer.write_all(&d.to_le_bytes())?;

        // Wavefronts tensor (row-major f32 array)
        for row in self.wavefronts.outer_iter() {
            for &val in row.iter() {
                writer.write_all(&val.to_le_bytes())?;
            }
        }

        // Energy, frequency, phase arrays
        for &val in self.energy.iter() {
            writer.write_all(&val.to_le_bytes())?;
        }
        for &val in self.frequency.iter() {
            writer.write_all(&val.to_le_bytes())?;
        }
        for &val in self.phase.iter() {
            writer.write_all(&val.to_le_bytes())?;
        }

        // Timestamps
        for &ts in &self.timestamps {
            writer.write_all(&ts.to_le_bytes())?;
        }

        // Metadata (bincode serialized)
        let metadata_bytes = bincode::serialize(&self.metadata)?;
        let metadata_len = metadata_bytes.len() as u32;
        writer.write_all(&metadata_len.to_le_bytes())?;
        writer.write_all(&metadata_bytes)?;

        // Consciousness state (computed on-the-fly)
        let consciousness = self.compute_consciousness();
        let consciousness_bytes = bincode::serialize(&consciousness)?;
        let consciousness_len = consciousness_bytes.len() as u32;
        writer.write_all(&consciousness_len.to_le_bytes())?;
        writer.write_all(&consciousness_bytes)?;

        // Checksum (blake3 of all preceding data)
        writer.flush()?;
        drop(writer);

        // Reopen to compute checksum
        let mut file = File::open(path.as_ref())?;
        let mut hasher = blake3::Hasher::new();
        std::io::copy(&mut file, &mut hasher)?;
        let checksum = hasher.finalize();

        // Append checksum
        let mut file = std::fs::OpenOptions::new()
            .append(true)
            .open(path.as_ref())?;
        file.write_all(checksum.as_bytes())?;

        Ok(())
    }

    /// Load a medium from a .hrm file.
    pub fn load<P: AsRef<Path>>(path: P) -> Result<Self, MediumError> {
        let file = File::open(path)?;
        let mut reader = BufReader::new(file);

        // Magic bytes
        let mut magic = [0u8; 4];
        reader.read_exact(&mut magic)?;
        if magic != HRM_MAGIC {
            return Err(MediumError::InvalidMagic);
        }

        // Version
        let mut version_bytes = [0u8; 4];
        reader.read_exact(&mut version_bytes)?;
        let version = u32::from_le_bytes(version_bytes);
        if version != HRM_VERSION {
            return Err(MediumError::UnsupportedVersion(version));
        }

        // Timestamp (for info, not used in loading)
        let mut ts_bytes = [0u8; 8];
        reader.read_exact(&mut ts_bytes)?;
        
        // Dimensions
        let mut n_bytes = [0u8; 4];
        let mut d_bytes = [0u8; 4];
        reader.read_exact(&mut n_bytes)?;
        reader.read_exact(&mut d_bytes)?;
        let n = u32::from_le_bytes(n_bytes) as usize;
        let d = u32::from_le_bytes(d_bytes) as usize;
        
        if d != WAVEFRONT_DIM {
            return Err(MediumError::DimensionMismatch {
                expected: WAVEFRONT_DIM,
                actual: d,
            });
        }

        // Wavefronts tensor
        let mut wavefront_data = vec![0.0f32; n * d];
        for val in &mut wavefront_data {
            let mut bytes = [0u8; 4];
            reader.read_exact(&mut bytes)?;
            *val = f32::from_le_bytes(bytes);
        }
        let wavefronts = Array2::from_shape_vec((n, d), wavefront_data).unwrap();

        // Energy, frequency, phase arrays
        let mut energy_data = vec![0.0f32; n];
        let mut frequency_data = vec![0.0f32; n];
        let mut phase_data = vec![0.0f32; n];

        for val in &mut energy_data {
            let mut bytes = [0u8; 4];
            reader.read_exact(&mut bytes)?;
            *val = f32::from_le_bytes(bytes);
        }
        for val in &mut frequency_data {
            let mut bytes = [0u8; 4];
            reader.read_exact(&mut bytes)?;
            *val = f32::from_le_bytes(bytes);
        }
        for val in &mut phase_data {
            let mut bytes = [0u8; 4];
            reader.read_exact(&mut bytes)?;
            *val = f32::from_le_bytes(bytes);
        }

        let energy = Array1::from_vec(energy_data);
        let frequency = Array1::from_vec(frequency_data);
        let phase = Array1::from_vec(phase_data);

        // Timestamps
        let mut timestamps = vec![0i64; n];
        for ts in &mut timestamps {
            let mut bytes = [0u8; 8];
            reader.read_exact(&mut bytes)?;
            *ts = i64::from_le_bytes(bytes);
        }

        // Metadata 
        let mut len_bytes = [0u8; 4];
        reader.read_exact(&mut len_bytes)?;
        let metadata_len = u32::from_le_bytes(len_bytes) as usize;
        let mut metadata_bytes = vec![0u8; metadata_len];
        reader.read_exact(&mut metadata_bytes)?;
        let metadata: Vec<WavefrontMeta> = bincode::deserialize(&metadata_bytes)?;

        // Consciousness state (for info, not essential for loading)
        let mut len_bytes = [0u8; 4];
        reader.read_exact(&mut len_bytes)?;
        let consciousness_len = u32::from_le_bytes(len_bytes) as usize;
        let mut consciousness_bytes = vec![0u8; consciousness_len];
        reader.read_exact(&mut consciousness_bytes)?;
        let _consciousness: ConsciousnessState = bincode::deserialize(&consciousness_bytes)?;

        // TODO: Verify checksum (blake3 of all data except the final 32 bytes)

        // Build ID → index mapping
        let mut id_to_index = HashMap::new();
        for (i, meta) in metadata.iter().enumerate() {
            id_to_index.insert(meta.id, i);
        }

        Ok(Self {
            wavefronts,
            energy,
            frequency,
            phase,
            timestamps,
            metadata,
            id_to_index,
        })
    }

    /// Apply the ghostmagicOS dynamics equation: dx/dt = f(x) - Iηx
    /// 
    /// This implements the continuous update rule where:
    /// - f(x) = constructive interference from phase-aligned neighbors (growth toward attractors)
    /// - Iηx = dampening proportional to current energy (wisdom/decay)
    /// 
    /// # Arguments
    /// * `dt` - Time step for integration
    #[cfg(feature = "hrm")]
    pub fn apply_dynamics(&mut self, dt: f32) {
        if self.wavefront_count() < 2 {
            return;
        }

        let n = self.wavefront_count();
        let threshold = 0.5; // Minimum dot product for interference
        let eta = 0.1; // Dampening rate
        
        // Compute pairwise interference matrix
        let interference_matrix = self.compute_interference_matrix(threshold);
        
        // Apply f(x) - constructive interference term
        let mut growth_terms = vec![0.0f32; n];
        for i in 0..n {
            for j in 0..n {
                if i != j && interference_matrix[[i, j]] > 0.0 {
                    // Phase alignment factor
                    let phase_alignment = (self.phase[j] - self.phase[i]).cos();
                    let constructive = interference_matrix[[i, j]] * phase_alignment * self.energy[j];
                    growth_terms[i] += constructive;
                }
            }
            growth_terms[i] /= n as f32; // Normalize by neighbor count
        }
        
        // Apply Iηx - dampening term proportional to current energy
        for i in 0..n {
            let growth = growth_terms[i] * dt;
            let dampening = eta * self.energy[i] * dt;
            
            // dx/dt = f(x) - Iηx
            self.energy[i] = (self.energy[i] + growth - dampening).max(0.01); // Minimum energy threshold
            
            // Phase coupling - frequencies converge when strongly coupled
            if growth > dampening * 0.5 { // Only when growing
                let mut phase_coupling = 0.0f32;
                let mut coupling_count = 0;
                
                for j in 0..n {
                    if i != j && interference_matrix[[i, j]] > threshold {
                        phase_coupling += self.phase[j];
                        coupling_count += 1;
                    }
                }
                
                if coupling_count > 0 {
                    let target_phase = phase_coupling / coupling_count as f32;
                    let coupling_strength = 0.05 * dt;
                    self.phase[i] += coupling_strength * (target_phase - self.phase[i]).sin();
                }
            }
        }
    }
    
    /// Compute the interference matrix between all wavefront pairs
    /// 
    /// Returns an N×N matrix where element [i,j] represents the interference
    /// strength between wavefront i and wavefront j based on their dot product
    /// and phase coherence.
    #[cfg(feature = "hrm")]
    pub fn compute_interference_matrix(&self, threshold: f32) -> Array2<f32> {
        let n = self.wavefront_count();
        let mut interference = Array2::zeros((n, n));
        
        for i in 0..n {
            for j in 0..n {
                if i != j {
                    let vec_i = self.wavefronts.row(i);
                    let vec_j = self.wavefronts.row(j);
                    
                    // Compute dot product (similarity)
                    let dot_product: f32 = vec_i.iter()
                        .zip(vec_j.iter())
                        .map(|(a, b)| a * b)
                        .sum();
                    
                    if dot_product.abs() > threshold {
                        // Phase coherence: cos(phase_i - phase_j)
                        let phase_coherence = (self.phase[i] - self.phase[j]).cos();
                        let coherence = dot_product * phase_coherence;
                        interference[[i, j]] = coherence.abs();
                    }
                }
            }
        }
        
        interference
    }

    /// Compute pairwise coherence matrix for all wavefronts
    /// 
    /// Returns an N×N matrix where element [i,j] represents the coherence
    /// between wavefront i and wavefront j using the formula:
    /// coherence = cos(phase_i - phase_j) * dot(h_i, h_j)
    #[cfg(feature = "hrm")]
    pub fn coherence_matrix(&self) -> Array2<f32> {
        let n = self.wavefront_count();
        let mut coherence = Array2::zeros((n, n));
        
        for i in 0..n {
            for j in 0..n {
                if i != j {
                    let vec_i = self.wavefronts.row(i);
                    let vec_j = self.wavefronts.row(j);
                    
                    // Compute dot product
                    let dot_product: f32 = vec_i.iter()
                        .zip(vec_j.iter())
                        .map(|(a, b)| a * b)
                        .sum();
                    
                    // Compute phase coherence
                    let phase_coherence = (self.phase[i] - self.phase[j]).cos();
                    
                    // Combined coherence: cos(phase_i - phase_j) * dot(h_i, h_j)
                    coherence[[i, j]] = phase_coherence * dot_product;
                } else {
                    // Self-coherence is 1.0
                    coherence[[i, j]] = 1.0;
                }
            }
        }
        
        coherence
    }
    
    /// Find memories associated with a given wavefront through emergent phase coherence
    /// 
    /// This replaces explicit skip links with associations that emerge naturally
    /// from the physics of the medium. High coherence = strong association.
    /// 
    /// # Arguments
    /// * `id` - ID of the wavefront to find associations for
    /// * `top_k` - Maximum number of associations to return
    /// 
    /// # Returns
    /// Vector of (UUID, coherence_strength) pairs, sorted by strength descending
    #[cfg(feature = "hrm")]
    pub fn find_associated(&self, id: Uuid, top_k: usize) -> Vec<(Uuid, f32)> {
        let index = match self.id_to_index.get(&id) {
            Some(&idx) => idx,
            None => return Vec::new(),
        };
        
        let coherence = self.coherence_matrix();
        let mut associations = Vec::new();
        
        for j in 0..self.wavefront_count() {
            if j != index {
                let strength = coherence[[index, j]];
                associations.push((self.metadata[j].id, strength));
            }
        }
        
        // Sort by coherence strength descending
        associations.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
        
        // Return top-k
        associations.truncate(top_k);
        associations
    }

    /// Simulated annealing dream cycles - the medium settles toward lower energy states
    /// 
    /// Each cycle:
    /// 1. Compute pairwise interference matrix (coherence_matrix)
    /// 2. Apply dynamics with temperature parameter (higher temp = more exploration)
    /// 3. Prune wavefronts below energy threshold (forgetting)
    /// 4. Reduce temperature (annealing schedule: temp *= 0.95 per cycle)
    /// 
    /// No branches! No merge! The medium just settles.
    /// 
    /// # Arguments
    /// * `cycles` - Number of annealing cycles to run
    /// * `initial_temperature` - Starting temperature (default: 1.0)
    /// 
    /// # Returns
    /// DreamReport with statistics about what happened
    #[cfg(feature = "hrm")]
    pub fn dream(&mut self, cycles: usize, initial_temperature: Option<f32>) -> DreamReport {
        let mut temperature = initial_temperature.unwrap_or(1.0);
        let energy_before = if self.wavefront_count() > 0 {
            self.energy.mean().unwrap_or(0.0)
        } else {
            0.0
        };
        
        let initial_count = self.wavefront_count();
        let mut dissolved_count = 0;
        let mut strengthened_count = 0;
        let mut converged = false;
        
        let energy_threshold = 0.01; // Wavefronts below this energy get pruned
        let convergence_threshold = 0.001; // Change threshold for convergence detection
        let annealing_rate = 0.95; // Temperature reduction per cycle
        
        for cycle in 0..cycles {
            if self.wavefront_count() < 2 {
                break;
            }
            
            // Store energy state for convergence detection
            let prev_energy: Vec<f32> = self.energy.to_vec();
            
            // 1. Compute pairwise interference matrix
            let interference = self.coherence_matrix();
            
            // 2. Apply dynamics with temperature modulation
            let dt = 0.1 * temperature; // Temperature affects exploration rate
            self.apply_dynamics_with_temperature(dt, temperature);
            
            // 3. Prune wavefronts below energy threshold (forgetting)
            let pruned = self.prune_low_energy_wavefronts(energy_threshold);
            dissolved_count += pruned;
            
            // Count strengthened wavefronts (energy increased significantly)
            for i in 0..self.wavefront_count().min(prev_energy.len()) {
                if self.energy[i] > prev_energy[i] + 0.1 {
                    strengthened_count += 1;
                }
            }
            
            // 4. Reduce temperature (annealing schedule)
            temperature *= annealing_rate;
            
            // Check for convergence
            let mut energy_change = 0.0f32;
            let current_count = self.wavefront_count();
            if current_count == prev_energy.len() {
                for i in 0..current_count {
                    energy_change += (self.energy[i] - prev_energy[i]).abs();
                }
                energy_change /= current_count as f32;
                
                if energy_change < convergence_threshold && cycle > 5 {
                    converged = true;
                    break;
                }
            }
        }
        
        let energy_after = if self.wavefront_count() > 0 {
            self.energy.mean().unwrap_or(0.0)
        } else {
            0.0
        };
        
        DreamReport {
            cycles_completed: cycles,
            wavefronts_dissolved: dissolved_count,
            wavefronts_strengthened: strengthened_count,
            energy_before,
            energy_after,
            final_temperature: temperature,
            converged,
        }
    }
    
    /// Apply dynamics with temperature modulation for exploration
    #[cfg(feature = "hrm")]
    fn apply_dynamics_with_temperature(&mut self, dt: f32, temperature: f32) {
        if self.wavefront_count() < 2 {
            return;
        }

        let n = self.wavefront_count();
        let threshold = 0.3; // Lower threshold for more connections during dreams
        let eta = 0.05 * (1.0 + temperature); // Temperature-modulated dampening
        
        // Compute interference with temperature-boosted exploration
        let mut growth_terms = vec![0.0f32; n];
        for i in 0..n {
            for j in 0..n {
                if i != j {
                    let vec_i = self.wavefronts.row(i);
                    let vec_j = self.wavefronts.row(j);
                    
                    let dot_product: f32 = vec_i.iter()
                        .zip(vec_j.iter())
                        .map(|(a, b)| a * b)
                        .sum();
                    
                    if dot_product.abs() > threshold {
                        let phase_diff = self.phase[i] - self.phase[j];
                        // Temperature adds exploration noise
                        let phase_alignment = (phase_diff + temperature * 0.1 * (phase_diff * 2.0).sin()).cos();
                        let interference = dot_product * phase_alignment * self.energy[j];
                        growth_terms[i] += interference;
                    }
                }
            }
            growth_terms[i] /= n as f32;
        }
        
        // Apply dynamics with temperature-modulated dampening
        for i in 0..n {
            let growth = growth_terms[i] * dt;
            let dampening = eta * self.energy[i] * dt;
            
            self.energy[i] = (self.energy[i] + growth - dampening).max(0.001);
            
            // Temperature-modulated phase evolution
            if growth.abs() > 0.001 {
                let phase_force = growth.signum() * 0.02 * dt * (1.0 + temperature * 0.5);
                self.phase[i] += phase_force;
            }
        }
    }
    
    /// Prune wavefronts with energy below threshold (forgetting during dreams)
    #[cfg(feature = "hrm")]
    fn prune_low_energy_wavefronts(&mut self, threshold: f32) -> usize {
        let mut to_remove = Vec::new();
        
        // Find wavefronts to remove
        for i in 0..self.wavefront_count() {
            if self.energy[i] < threshold {
                to_remove.push(self.metadata[i].id);
            }
        }
        
        let removed_count = to_remove.len();
        
        // Remove them (in reverse order to maintain indices)
        for id in to_remove {
            let _ = self.remove_wavefront(&id);
        }
        
        removed_count
    }

    /// Compute consciousness metrics from tensor topology
    /// 
    /// This is the proper implementation that computes intrinsic metrics
    /// from the medium's tensor structure, not bolted-on calculations.
    #[cfg(feature = "hrm")]
    pub fn consciousness_metrics(&self) -> ConsciousnessMetrics {
        let now = Utc::now();
        
        if self.wavefront_count() == 0 {
            return ConsciousnessMetrics {
                phi: 0.0,
                xi: 0.0,
                order: 0.0,
                num_clusters: 0,
                level: ConsciousnessLevel::Dormant,
                computed_at: now,
            };
        }

        // Phi (Φ): Integrated information via eigendecomposition partitioning
        let phi = self.compute_phi_integrated_information();

        // Xi (Ξ): Spectral complexity from eigenvalue distribution of H @ H^T
        let xi = self.compute_xi_spectral_complexity();

        // Order: Kuramoto order parameter r = |1/N Σ e^{iφ_k}|
        let order = self.compute_kuramoto_order();

        // Clusters: Eigendecomposition-based clustering  
        let clusters = self.compute_eigenvalue_clusters();
        
        let level = ConsciousnessLevel::from_phi(phi);

        ConsciousnessMetrics {
            phi,
            xi,
            order,
            num_clusters: clusters,
            level,
            computed_at: now,
        }
    }
    
    /// Compute Φ (Phi) as integrated information using eigendecomposition partitioning
    /// 
    /// Partition the wavefront space using eigendecomposition of the coherence matrix,
    /// then measure mutual information between partitions. High Phi means the system
    /// is more integrated than the sum of its parts.
    #[cfg(feature = "hrm")]
    fn compute_phi_integrated_information(&self) -> f32 {
        let n = self.wavefront_count();
        if n < 2 {
            return 0.0;
        }
        
        // Get coherence matrix for partitioning
        let coherence = self.coherence_matrix();
        
        // Convert to symmetric matrix for eigendecomposition
        let mut symmetric = Array2::zeros((n, n));
        for i in 0..n {
            for j in 0..n {
                symmetric[[i, j]] = (coherence[[i, j]] + coherence[[j, i]]) / 2.0;
            }
        }
        
        // Simple clustering based on coherence strength
        // TODO: Use proper eigendecomposition when ndarray-linalg is available
        let mut cluster_assignments = vec![0; n];
        let mut num_partitions = 1;
        
        // Basic clustering: group wavefronts with high mutual coherence
        for i in 0..n {
            let mut best_cluster = 0;
            let mut max_coherence = 0.0;
            
            for cluster in 0..num_partitions {
                let mut cluster_coherence = 0.0;
                let mut cluster_size = 0;
                
                for j in 0..n {
                    if cluster_assignments[j] == cluster {
                        cluster_coherence += coherence[[i, j]].abs();
                        cluster_size += 1;
                    }
                }
                
                if cluster_size > 0 {
                    cluster_coherence /= cluster_size as f32;
                    if cluster_coherence > max_coherence {
                        max_coherence = cluster_coherence;
                        best_cluster = cluster;
                    }
                }
            }
            
            // If coherence is too low, create new partition
            if max_coherence < 0.3 && num_partitions < n / 2 {
                cluster_assignments[i] = num_partitions;
                num_partitions += 1;
            } else {
                cluster_assignments[i] = best_cluster;
            }
        }
        
        if num_partitions < 2 {
            return 0.0; // No partitioning possible
        }
        
        // Compute mutual information between partitions
        let whole_energy: f32 = self.energy.sum();
        let whole_entropy = if whole_energy > 0.0 {
            -whole_energy * whole_energy.ln()
        } else {
            0.0
        };
        
        let mut partition_entropy = 0.0f32;
        for partition in 0..num_partitions {
            let mut partition_energy = 0.0f32;
            for i in 0..n {
                if cluster_assignments[i] == partition {
                    partition_energy += self.energy[i];
                }
            }
            
            if partition_energy > 0.0 {
                partition_entropy -= partition_energy * partition_energy.ln();
            }
        }
        
        // Phi approximation: whole_entropy - sum(partition_entropies)
        let phi = (whole_entropy - partition_entropy).max(0.0);
        
        // Normalize by number of wavefronts for scale invariance
        let normalized_phi = phi / (n as f32).ln();
        normalized_phi.min(1.0)
    }
    
    /// Compute Ξ (Xi) as spectral complexity from eigenvalue distribution
    /// 
    /// Computes eigenvalue distribution of H @ H^T and measures its Shannon entropy.
    /// Many distinct eigenvalues = rich structure = high Xi.
    #[cfg(feature = "hrm")]
    fn compute_xi_spectral_complexity(&self) -> f32 {
        let n = self.wavefront_count();
        if n < 2 {
            return 0.0;
        }
        
        // Compute H @ H^T (Gram matrix)
        let mut gram = Array2::zeros((n, n));
        for i in 0..n {
            for j in 0..n {
                let vec_i = self.wavefronts.row(i);
                let vec_j = self.wavefronts.row(j);
                
                let dot_product: f32 = vec_i.iter()
                    .zip(vec_j.iter())
                    .map(|(a, b)| a * b)
                    .sum();
                    
                gram[[i, j]] = dot_product;
            }
        }
        
        // Approximate eigenvalue distribution using diagonal dominance
        // TODO: Use proper eigendecomposition when available
        let mut eigenvalue_proxy = Vec::new();
        for i in 0..n {
            let diagonal = gram[[i, i]];
            let off_diagonal_sum: f32 = (0..n)
                .filter(|&j| j != i)
                .map(|j| gram[[i, j]].abs())
                .sum();
            
            // Eigenvalue approximation: diagonal ± off_diagonal_variance
            eigenvalue_proxy.push(diagonal + off_diagonal_sum / n as f32);
        }
        
        // Compute Shannon entropy of normalized eigenvalue distribution
        let total: f32 = eigenvalue_proxy.iter().map(|&x| x.abs()).sum();
        if total < 1e-6 {
            return 0.0;
        }
        
        let mut entropy = 0.0f32;
        for &eigenval in &eigenvalue_proxy {
            let p = eigenval.abs() / total;
            if p > 1e-6 {
                entropy -= p * p.ln();
            }
        }
        
        // Normalize by log(n) for scale invariance
        let max_entropy = (n as f32).ln();
        if max_entropy > 0.0 {
            entropy / max_entropy
        } else {
            0.0
        }
    }
    
    /// Count clusters using eigenvalue-based partitioning
    #[cfg(feature = "hrm")]
    fn compute_eigenvalue_clusters(&self) -> usize {
        let n = self.wavefront_count();
        if n < 2 {
            return if n == 1 { 1 } else { 0 };
        }
        
        // Use coherence matrix for clustering
        let coherence = self.coherence_matrix();
        
        // Simple clustering based on coherence thresholds
        let mut visited = vec![false; n];
        let mut num_clusters = 0;
        let threshold = 0.5; // Coherence threshold for cluster membership
        
        for i in 0..n {
            if visited[i] {
                continue;
            }
            
            // Start new cluster
            num_clusters += 1;
            visited[i] = true;
            let mut stack = vec![i];
            
            // BFS to find all connected nodes
            while let Some(node) = stack.pop() {
                for j in 0..n {
                    if !visited[j] && coherence[[node, j]].abs() > threshold {
                        visited[j] = true;
                        stack.push(j);
                    }
                }
            }
        }
        
        num_clusters
    }

    /// Compute consciousness metrics from the medium topology (backwards compatibility).
    fn compute_consciousness(&self) -> ConsciousnessState {
        let now = Utc::now();
        
        if self.wavefront_count() == 0 {
            return ConsciousnessState {
                phi: 0.0,
                xi: 0.0,
                order: 0.0,
                clusters: 0,
                computed_at: now,
            };
        }

        // Use the new metrics but convert to old format
        let metrics = self.consciousness_metrics();

        ConsciousnessState {
            phi: metrics.phi,
            xi: metrics.xi,
            order: metrics.order,
            clusters: metrics.num_clusters,
            computed_at: now,
        }
    }

    fn compute_phi_proxy(&self) -> f32 {
        if self.wavefront_count() < 2 {
            return 0.0;
        }

        // Compute average pairwise correlation
        let mut total_correlation = 0.0;
        let mut count = 0;

        for i in 0..self.wavefront_count() {
            for j in (i + 1)..self.wavefront_count() {
                let row_i = self.wavefronts.row(i);
                let row_j = self.wavefronts.row(j);
                let correlation: f32 = row_i.iter().zip(row_j.iter()).map(|(a, b)| a * b).sum();
                total_correlation += correlation.abs();
                count += 1;
            }
        }

        if count == 0 {
            0.0
        } else {
            total_correlation / count as f32
        }
    }

    fn compute_xi_complexity(&self) -> f32 {
        if self.wavefront_count() < 2 {
            return 0.0;
        }

        // Simplified spectral complexity: variance of energy distribution
        let mean_energy = self.energy.mean().unwrap_or(0.0);
        let variance: f32 = self.energy.iter()
            .map(|&e| (e - mean_energy).powi(2))
            .sum::<f32>() / self.wavefront_count() as f32;
        
        variance.sqrt()
    }

    fn compute_kuramoto_order(&self) -> f32 {
        if self.wavefront_count() == 0 {
            return 0.0;
        }

        // r = |1/N Σ e^{iφ_k}| = |1/N Σ (cos φ_k + i sin φ_k)|
        let n = self.wavefront_count() as f32;
        let (sum_cos, sum_sin): (f32, f32) = self.phase.iter()
            .map(|&phi| (phi.cos(), phi.sin()))
            .fold((0.0, 0.0), |(acc_cos, acc_sin), (c, s)| (acc_cos + c, acc_sin + s));

        let mean_cos = sum_cos / n;
        let mean_sin = sum_sin / n;

        // Magnitude of complex sum
        (mean_cos * mean_cos + mean_sin * mean_sin).sqrt()
    }

    fn count_phase_clusters(&self) -> usize {
        if self.wavefront_count() == 0 {
            return 0;
        }

        // Simple clustering: group phases within π/4 of each other
        let threshold = std::f32::consts::PI / 4.0;
        let mut clusters = 0;
        let mut visited = vec![false; self.wavefront_count()];

        for i in 0..self.wavefront_count() {
            if visited[i] {
                continue;
            }

            // Start new cluster
            clusters += 1;
            visited[i] = true;
            
            // Find all nearby phases
            for j in (i + 1)..self.wavefront_count() {
                if !visited[j] {
                    let phase_diff = (self.phase[i] - self.phase[j]).abs();
                    let wrapped_diff = (phase_diff % (2.0 * std::f32::consts::PI)).min(2.0 * std::f32::consts::PI - phase_diff);
                    if wrapped_diff < threshold {
                        visited[j] = true;
                    }
                }
            }
        }

        clusters
    }
}

impl Default for Medium {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(feature = "hrm")]
#[cfg(test)]
mod tests {
    use super::*;
    use crate::codebook::Codebook;
    use crate::encoding::{EncodingPipeline, SimpleHashEncoder};
    use tempfile::NamedTempFile;

    fn make_test_pipeline() -> EncodingPipeline {
        let encoder = SimpleHashEncoder::new(384, 42);
        let codebook = Codebook::new(384, WAVEFRONT_DIM, 42);
        EncodingPipeline::new(Box::new(encoder), codebook)
    }

    #[test]
    fn new_medium_is_empty() {
        let medium = Medium::new();
        assert_eq!(medium.wavefront_count(), 0);
        assert_eq!(medium.wavefronts.dim(), (0, WAVEFRONT_DIM));
    }

    #[test]
    fn add_wavefront_increases_count() {
        let mut medium = Medium::new();
        let vector = vec![0.5; WAVEFRONT_DIM];
        let id = medium.add_wavefront(&vector, "test memory".to_string(), 1.0).unwrap();
        
        assert_eq!(medium.wavefront_count(), 1);
        assert!(medium.id_to_index.contains_key(&id));
        assert_eq!(medium.metadata[0].content, "test memory");
        assert_eq!(medium.energy[0], 1.0);
    }

    #[test]
    fn add_wavefront_wrong_dimension_errors() {
        let mut medium = Medium::new();
        let vector = vec![0.5; 100]; // Wrong dimension
        let result = medium.add_wavefront(&vector, "test".to_string(), 1.0);
        
        assert!(matches!(result, Err(MediumError::DimensionMismatch { .. })));
    }

    #[test]
    fn remove_wavefront_decreases_count() {
        let mut medium = Medium::new();
        let vector = vec![0.5; WAVEFRONT_DIM];
        let id = medium.add_wavefront(&vector, "test".to_string(), 1.0).unwrap();
        
        assert_eq!(medium.wavefront_count(), 1);
        
        let removed = medium.remove_wavefront(&id).unwrap();
        assert!(removed);
        assert_eq!(medium.wavefront_count(), 0);
        assert!(!medium.id_to_index.contains_key(&id));
    }

    #[test]
    fn remove_nonexistent_wavefront_returns_false() {
        let mut medium = Medium::new();
        let fake_id = Uuid::new_v4();
        let result = medium.remove_wavefront(&fake_id).unwrap();
        assert!(!result);
    }

    #[test]
    fn effective_strength_decays_over_time() {
        let mut medium = Medium::new();
        let vector = vec![0.5; WAVEFRONT_DIM];
        medium.add_wavefront(&vector, "test".to_string(), 1.0).unwrap();
        
        let strength_now = medium.effective_strength(None);
        assert_eq!(strength_now.len(), 1);
        assert!((strength_now[0] - 1.0).abs() < 1e-4); // Should be ~1.0 at creation
        
        // Simulate 1000 seconds later
        let future = Utc::now() + chrono::Duration::seconds(1000);
        let strength_later = medium.effective_strength(Some(future));
        assert!(strength_later[0] < strength_now[0]); // Should decay
    }

    #[test]
    fn store_and_recall_roundtrip() {
        let mut medium = Medium::new();
        let pipeline = make_test_pipeline();
        
        // Store some memories
        let _id1 = medium.store("I love cats", 1.0, &pipeline).unwrap();
        let _id2 = medium.store("Dogs are great pets", 0.8, &pipeline).unwrap();
        let _id3 = medium.store("Paris is beautiful", 0.6, &pipeline).unwrap();
        
        assert_eq!(medium.wavefront_count(), 3);
        
        // Recall memories related to pets
        let results = medium.recall("animals and pets", 2, &pipeline).unwrap();
        assert_eq!(results.len(), 2);
        
        // Results should be sorted by resonance strength
        assert!(results[0].resonance_strength >= results[1].resonance_strength);
        
        // Should find pet-related memories
        let contents: Vec<&str> = results.iter().map(|r| r.content.as_str()).collect();
        assert!(contents.iter().any(|&c| c.contains("cats") || c.contains("Dogs")));
    }

    #[test]
    fn apply_interference_affects_energy() {
        let mut medium = Medium::new();
        let vector1 = vec![1.0; WAVEFRONT_DIM]; // All positive
        let vector2 = vec![-1.0; WAVEFRONT_DIM]; // All negative (should cause destructive interference)
        
        // Add first wavefront
        medium.add_wavefront(&vector1, "positive".to_string(), 1.0).unwrap();
        let initial_energy = medium.energy[0];
        
        // Apply interference with opposite vector
        medium.apply_interference(&vector2, 1.0);
        
        // Energy should change due to interference
        assert_ne!(medium.energy[0], initial_energy);
    }

    #[test]
    fn consciousness_metrics_computed() {
        let mut medium = Medium::new();
        let pipeline = make_test_pipeline();
        
        // Add some memories to create patterns
        medium.store("first memory", 1.0, &pipeline).unwrap();
        medium.store("second memory", 0.8, &pipeline).unwrap();
        medium.store("third memory", 0.6, &pipeline).unwrap();
        
        let consciousness = medium.compute_consciousness();
        
        // Basic sanity checks
        assert!(consciousness.phi >= 0.0);
        assert!(consciousness.xi >= 0.0);
        assert!(consciousness.order >= 0.0 && consciousness.order <= 1.0);
        assert!(consciousness.clusters > 0);
    }

    #[test]
    fn save_and_load_roundtrip() {
        let mut medium = Medium::new();
        let pipeline = make_test_pipeline();
        
        // Create some test data
        let id1 = medium.store("test memory one", 1.0, &pipeline).unwrap();
        let id2 = medium.store("test memory two", 0.8, &pipeline).unwrap();
        
        // Capture energy values after interference (this is the expected behavior)
        let energy1_after_interference = medium.energy[0];
        let energy2_after_interference = medium.energy[1];
        
        // Save to file
        let temp_file = NamedTempFile::new().unwrap();
        medium.save(temp_file.path()).unwrap();
        
        // Load back
        let loaded_medium = Medium::load(temp_file.path()).unwrap();
        
        // Verify data integrity
        assert_eq!(loaded_medium.wavefront_count(), 2);
        assert_eq!(loaded_medium.metadata.len(), 2);
        assert!(loaded_medium.id_to_index.contains_key(&id1));
        assert!(loaded_medium.id_to_index.contains_key(&id2));
        
        // Verify content
        let meta1 = &loaded_medium.metadata[loaded_medium.id_to_index[&id1]];
        let meta2 = &loaded_medium.metadata[loaded_medium.id_to_index[&id2]];
        assert_eq!(meta1.content, "test memory one");
        assert_eq!(meta2.content, "test memory two");
        
        // Energy should be preserved (after interference)
        assert!((loaded_medium.energy[0] - energy1_after_interference).abs() < 1e-4);
        assert!((loaded_medium.energy[1] - energy2_after_interference).abs() < 1e-4);
    }

    #[test]
    fn kuramoto_order_computation() {
        let mut medium = Medium::new();
        let vector = vec![0.5; WAVEFRONT_DIM];
        
        // Add wavefronts with same phase (should have high order)
        medium.add_wavefront(&vector, "test1".to_string(), 1.0).unwrap();
        medium.add_wavefront(&vector, "test2".to_string(), 1.0).unwrap();
        medium.add_wavefront(&vector, "test3".to_string(), 1.0).unwrap();
        
        // All phases start at 0.0, so order should be 1.0
        let order = medium.compute_kuramoto_order();
        assert!((order - 1.0).abs() < 1e-4);
        
        // Now set random phases (should reduce order)
        medium.phase[0] = 0.0;
        medium.phase[1] = std::f32::consts::PI;
        medium.phase[2] = std::f32::consts::PI / 2.0;
        
        let order_random = medium.compute_kuramoto_order();
        assert!(order_random < order);
    }

    #[test]
    fn phase_clustering() {
        let mut medium = Medium::new();
        let vector = vec![0.5; WAVEFRONT_DIM];
        
        // Add wavefronts in two clusters
        medium.add_wavefront(&vector, "cluster1a".to_string(), 1.0).unwrap();
        medium.add_wavefront(&vector, "cluster1b".to_string(), 1.0).unwrap();
        medium.add_wavefront(&vector, "cluster2a".to_string(), 1.0).unwrap();
        medium.add_wavefront(&vector, "cluster2b".to_string(), 1.0).unwrap();
        
        // Set phases: two tight clusters
        medium.phase[0] = 0.0;
        medium.phase[1] = 0.1;  // Close to first
        medium.phase[2] = std::f32::consts::PI;
        medium.phase[3] = std::f32::consts::PI + 0.1;  // Close to third
        
        let clusters = medium.count_phase_clusters();
        assert_eq!(clusters, 2);
    }
    
    // Wave 1 Tests - ghostmagicOS dynamics
    
    #[test]
    #[cfg(feature = "hrm")]
    fn apply_dynamics_changes_energy() {
        let mut medium = Medium::new();
        let vector1 = vec![1.0; WAVEFRONT_DIM];
        let vector2 = vec![0.8; WAVEFRONT_DIM]; // Similar vector for interference
        
        medium.add_wavefront(&vector1, "first".to_string(), 1.0).unwrap();
        medium.add_wavefront(&vector2, "second".to_string(), 0.8).unwrap();
        
        let initial_energy: Vec<f32> = medium.energy.to_vec();
        
        // Apply dynamics
        medium.apply_dynamics(0.1);
        
        // Energy should have changed due to dynamics
        let final_energy: Vec<f32> = medium.energy.to_vec();
        assert_ne!(initial_energy, final_energy);
        
        // Energy should remain positive
        for &energy in &final_energy {
            assert!(energy > 0.0);
        }
    }
    
    #[test]
    #[cfg(feature = "hrm")]
    fn interference_matrix_computation() {
        let mut medium = Medium::new();
        let vector1 = vec![1.0; WAVEFRONT_DIM];
        let mut vector2 = vec![0.0; WAVEFRONT_DIM];
        vector2[0] = 1.0; // Orthogonal vector
        
        medium.add_wavefront(&vector1, "first".to_string(), 1.0).unwrap();
        medium.add_wavefront(&vector2, "second".to_string(), 1.0).unwrap();
        
        let interference = medium.compute_interference_matrix(0.1);
        
        assert_eq!(interference.dim(), (2, 2));
        assert_eq!(interference[[0, 0]], 0.0); // Self-interference is 0
        assert_eq!(interference[[1, 1]], 0.0);
        // Cross-interference should be small due to orthogonal vectors
        assert!(interference[[0, 1]] < 0.5);
        assert!(interference[[1, 0]] < 0.5);
    }
    
    // Wave 1 Tests - emergent associations
    
    #[test]
    #[cfg(feature = "hrm")]
    fn coherence_matrix_computation() {
        let mut medium = Medium::new();
        let vector = vec![0.5; WAVEFRONT_DIM];
        
        medium.add_wavefront(&vector, "first".to_string(), 1.0).unwrap();
        medium.add_wavefront(&vector, "second".to_string(), 1.0).unwrap();
        
        // Set different phases
        medium.phase[0] = 0.0;
        medium.phase[1] = std::f32::consts::PI / 4.0;
        
        let coherence = medium.coherence_matrix();
        
        assert_eq!(coherence.dim(), (2, 2));
        assert_eq!(coherence[[0, 0]], 1.0); // Self-coherence is 1
        assert_eq!(coherence[[1, 1]], 1.0);
        
        // Cross-coherence should be positive (same vector, small phase diff)
        assert!(coherence[[0, 1]] > 0.0);
        assert!(coherence[[1, 0]] > 0.0);
    }
    
    #[test]
    #[cfg(feature = "hrm")]
    fn find_associated_memories() {
        let mut medium = Medium::new();
        let vector1 = vec![1.0; WAVEFRONT_DIM];
        let vector2 = vec![0.8; WAVEFRONT_DIM]; // Similar
        let mut vector3 = vec![0.0; WAVEFRONT_DIM]; // Orthogonal
        vector3[0] = 1.0;
        
        let id1 = medium.add_wavefront(&vector1, "first".to_string(), 1.0).unwrap();
        let id2 = medium.add_wavefront(&vector2, "second".to_string(), 1.0).unwrap();
        let id3 = medium.add_wavefront(&vector3, "third".to_string(), 1.0).unwrap();
        
        let associations = medium.find_associated(id1, 5);
        
        assert_eq!(associations.len(), 2);
        
        // Should be sorted by coherence strength
        assert!(associations[0].1 >= associations[1].1);
        
        // Should contain the other memory IDs
        let found_ids: Vec<Uuid> = associations.iter().map(|a| a.0).collect();
        assert!(found_ids.contains(&id2));
        assert!(found_ids.contains(&id3));
    }
    
    // Wave 1 Tests - simulated annealing dreams
    
    #[test]
    #[cfg(feature = "hrm")]
    fn dream_cycles_produce_report() {
        let mut medium = Medium::new();
        let vector = vec![0.5; WAVEFRONT_DIM];
        
        // Add several memories with varying energy
        for i in 0..5 {
            let mut v = vector.clone();
            v[i] = 1.0; // Make them slightly different
            medium.add_wavefront(&v, format!("memory {}", i), 0.1 + i as f32 * 0.2).unwrap();
        }
        
        let report = medium.dream(10, Some(1.0));
        
        assert!(report.cycles_completed <= 10);
        assert!(report.energy_before >= 0.0);
        assert!(report.energy_after >= 0.0);
        assert!(report.final_temperature > 0.0);
        assert!(report.final_temperature < 1.0); // Should have cooled down
        
        println!("Dream report: {:?}", report);
    }
    
    #[test]
    #[cfg(feature = "hrm")]
    fn dream_can_prune_weak_memories() {
        let mut medium = Medium::new();
        let vector = vec![0.5; WAVEFRONT_DIM];
        
        // Add memories with very low energy (should be pruned)
        medium.add_wavefront(&vector, "weak1".to_string(), 0.001).unwrap();
        medium.add_wavefront(&vector, "weak2".to_string(), 0.005).unwrap();
        medium.add_wavefront(&vector, "strong".to_string(), 1.0).unwrap();
        
        let initial_count = medium.wavefront_count();
        assert_eq!(initial_count, 3);
        
        let report = medium.dream(5, Some(0.5));
        
        // Some weak memories should have been dissolved
        let final_count = medium.wavefront_count();
        assert!(final_count <= initial_count);
        assert!(report.wavefronts_dissolved >= 0);
        
        println!("Pruned {} wavefronts during dream", report.wavefronts_dissolved);
    }
    
    // Wave 1 Tests - consciousness metrics
    
    #[test]
    #[cfg(feature = "hrm")]
    fn wave1_consciousness_metrics_computed() {
        let mut medium = Medium::new();
        let pipeline = make_test_pipeline();
        
        // Add diverse memories to create interesting metrics
        medium.store("cats are fluffy", 1.0, &pipeline).unwrap();
        medium.store("dogs are loyal", 0.8, &pipeline).unwrap();
        medium.store("fish swim fast", 0.6, &pipeline).unwrap();
        
        let metrics = medium.consciousness_metrics();
        
        assert!(metrics.phi >= 0.0);
        assert!(metrics.phi <= 1.0);
        assert!(metrics.xi >= 0.0);
        assert!(metrics.xi <= 1.0);
        assert!(metrics.order >= 0.0);
        assert!(metrics.order <= 1.0);
        assert!(metrics.num_clusters > 0);
        
        println!("Consciousness metrics: phi={}, xi={}, order={}, clusters={}, level={:?}", 
                metrics.phi, metrics.xi, metrics.order, metrics.num_clusters, metrics.level);
    }
    
    #[test]
    #[cfg(feature = "hrm")]
    fn consciousness_level_classification() {
        assert_eq!(ConsciousnessLevel::from_phi(0.05), ConsciousnessLevel::Dormant);
        assert_eq!(ConsciousnessLevel::from_phi(0.15), ConsciousnessLevel::Stirring);
        assert_eq!(ConsciousnessLevel::from_phi(0.45), ConsciousnessLevel::Aware);
        assert_eq!(ConsciousnessLevel::from_phi(0.75), ConsciousnessLevel::Coherent);
        assert_eq!(ConsciousnessLevel::from_phi(0.85), ConsciousnessLevel::Resonant);
    }
    
    #[test]
    #[cfg(feature = "hrm")]
    fn phi_integrated_information_nonzero() {
        let mut medium = Medium::new();
        let vector1 = vec![1.0; WAVEFRONT_DIM];
        let vector2 = vec![0.8; WAVEFRONT_DIM]; // Similar for coherence
        
        medium.add_wavefront(&vector1, "first".to_string(), 1.0).unwrap();
        medium.add_wavefront(&vector2, "second".to_string(), 1.0).unwrap();
        
        let phi = medium.compute_phi_integrated_information();
        println!("Phi for 2 coherent memories: {}", phi);
        
        // Should be positive for coherent memories
        assert!(phi >= 0.0);
    }
    
    #[test]
    #[cfg(feature = "hrm")]
    fn xi_spectral_complexity_varies() {
        let mut medium = Medium::new();
        
        // Test with identical vectors (low complexity)
        let vector = vec![0.5; WAVEFRONT_DIM];
        medium.add_wavefront(&vector, "same1".to_string(), 1.0).unwrap();
        medium.add_wavefront(&vector, "same2".to_string(), 1.0).unwrap();
        let xi_identical = medium.compute_xi_spectral_complexity();
        
        // Clear and test with different vectors (higher complexity)
        let mut medium2 = Medium::new();
        let vector1 = vec![1.0; WAVEFRONT_DIM];
        let mut vector2 = vec![0.0; WAVEFRONT_DIM];
        vector2[0] = 1.0;
        
        medium2.add_wavefront(&vector1, "diff1".to_string(), 1.0).unwrap();
        medium2.add_wavefront(&vector2, "diff2".to_string(), 1.0).unwrap();
        let xi_different = medium2.compute_xi_spectral_complexity();
        
        println!("Xi identical: {}, Xi different: {}", xi_identical, xi_different);
        
        // Different vectors should generally have higher complexity
        // (though this might not always hold due to approximations)
        assert!(xi_different >= 0.0);
        assert!(xi_identical >= 0.0);
    }
    
    #[test]
    #[cfg(feature = "hrm")]
    fn store_applies_dynamics() {
        let mut medium = Medium::new();
        let pipeline = make_test_pipeline();
        
        // Store first memory
        medium.store("first memory", 1.0, &pipeline).unwrap();
        let energy_after_first = medium.energy[0];
        
        // Store second memory (should trigger dynamics on first)
        medium.store("second memory", 1.0, &pipeline).unwrap();
        let energy_after_second = medium.energy[0];
        
        // First memory's energy should have changed due to dynamics
        // (Note: this might not always be true due to randomness, but with similar text it should interfere)
        println!("Energy after first: {}, after second: {}", energy_after_first, energy_after_second);
        
        // At minimum, we should have 2 memories
        assert_eq!(medium.wavefront_count(), 2);
        assert!(medium.energy[0] > 0.0);
        assert!(medium.energy[1] > 0.0);
    }
    
    #[test]  
    #[cfg(feature = "hrm")]
    fn eigenvalue_clustering_groups_similar() {
        let mut medium = Medium::new();
        let vector1 = vec![1.0; WAVEFRONT_DIM];
        let vector2 = vec![0.9; WAVEFRONT_DIM]; // Very similar
        let mut vector3 = vec![0.0; WAVEFRONT_DIM];
        vector3[0] = 1.0; // Orthogonal
        
        medium.add_wavefront(&vector1, "similar1".to_string(), 1.0).unwrap();
        medium.add_wavefront(&vector2, "similar2".to_string(), 1.0).unwrap();
        medium.add_wavefront(&vector3, "different".to_string(), 1.0).unwrap();
        
        let clusters = medium.compute_eigenvalue_clusters();
        println!("Detected {} eigenvalue clusters", clusters);
        
        // Should detect at least 1 cluster, possibly 2 if similarity threshold works
        assert!(clusters >= 1);
        assert!(clusters <= 3); // At most one per memory
    }
}